### PR TITLE
toJSON method support

### PR DESCRIPTION
**Pull request by roeycohen**
added to the encoder support for objects with toJSON method.

### CODE REVIEW

**Comment by roeycohen** [comment]
i'm not sure how to fix this...
are the tests using objects with toJSON method?

**Comment by darrachequesne** [comment]
I think that's because `Buffer` have a `toJSON` method. How about moving it after the `Buffer` and `ArrayBuffer` checks [there](https://github.com/roeycohen/notepack/blob/ff9f0abdf46741281dec8c82602c9fbe9df8b9d5/lib/encode.js#L254)?

Also, shouldn't it rather be `return _encode(value.toJSON())`? Besides, could you please add a test case, and also update the browser file [here](https://github.com/darrachequesne/notepack/blob/master/browser/encode.js)? Thanks!

**Comment by roeycohen** [comment]
ok, i've made the change. now all tests are passed.

toJSON might return Buffers and Dates and all kind of things and i wanted it to support these cases...

**Comment by roeycohen** [comment]
> return _encode(value.toJSON())
this is the same as putting the toJSON at the beginning of the _encode method and we also have the initial call from encode.

i'll write a few more tests and push again.

**Comment by roeycohen** [comment]
ok, added a new test.
hope now everything is ready for merging :)

**Comment by roeycohen** [comment]
well that's weird... i've only changed indentation in test file...

**Comment by darrachequesne** [comment]
@roeycohen I implemented it a bit differently, please see https://github.com/darrachequesne/notepack/pull/8

I think the failure was due to a timeout during the tests, so I increased the value [here](https://github.com/darrachequesne/notepack/blob/master/test/test.js#L282).

Again, thanks :+1:

**Comment by roeycohen** [comment]
seems great :)
to bad i didn't notice the "return" call at the end of each type...

**Comment by roeycohen** [comment]
it will be nice to update the package.json file of https://github.com/socketio/socket.io-redis/blob/master/package.json to the latest release of this plugin.

**Pull request closed without merging**
